# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def all_pods
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    inhibit_all_warnings!
    
    # Pods 
    pod 'Alamofire', '~> 4.7'
    pod 'KeychainSwift'
    pod 'TextFieldEffects'
    pod 'DCKit'
    pod 'EGFormValidator'
    pod 'SwiftGen'
end

target 'kacagiderim_beta' do
	all_pods
end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
