# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def all_pods
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    inhibit_all_warnings!
    
    # Pods 
    pod 'Alamofire', '~> 4.7'
    pod 'TextFieldEffects'
    pod 'DCKit'
end

target 'kacagiderim_beta' do
	all_pods
end
