# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def all_pods
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    inhibit_all_warnings!
    
    # Pods 
    pod 'Alamofire', '~> 4.7'
    pod 'GoogleSignIn'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'KeychainSwift'
    pod 'TextFieldEffects'
    pod 'DCKit'
    pod 'EGFormValidator'
    pod 'SwiftGen'
    pod 'NVActivityIndicatorView'
    pod 'Dodo', '~> 11.0'
    pod 'CHIPageControl', '~> 0.1.3'
    pod 'McPicker','~> 0.5.1'
    pod 'CardParts'
    pod 'Kingfisher', '~> 4.0'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
end

target 'kacagiderim_beta' do
	all_pods
end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
