# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def all_pods
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    inhibit_all_warnings!
    
    # Pods 
    pod 'Alamofire', '~> 4.7'
end

target 'testlogin' do
  all_pods
end

target 'testloginTests' do
  all_pods
end

target 'testloginUITests' do
  all_pods
end
